//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fibremex.com.mx/", ConfigurationName="ServiceReference1.WS_EcommerceSoap")]
    public interface WS_EcommerceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/CreatePedidoB2C", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2CResponse> CreatePedidoB2CAsync(ServiceReference1.CreatePedidoB2CRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/CreatePedidoB2B", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BResponse> CreatePedidoB2BAsync(ServiceReference1.CreatePedidoB2BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/CreatePedidoB2B_withoutCredit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditResponse> CreatePedidoB2B_withoutCreditAsync(ServiceReference1.CreatePedidoB2B_withoutCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/UpdateRefDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateRefDeliveryResponse> UpdateRefDeliveryAsync(ServiceReference1.UpdateRefDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/GetInforWs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ResponseString> GetInforWsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/AddCotizacionFirmeB2B", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.AddCotizacionFirmeB2BResponse> AddCotizacionFirmeB2BAsync(ServiceReference1.AddCotizacionFirmeB2BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/UpdateCotizacionFirmeB2B", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateCotizacionFirmeB2BResponse> UpdateCotizacionFirmeB2BAsync(ServiceReference1.UpdateCotizacionFirmeB2BRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/CreatePedidoB2BFirme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BFirmeResponse> CreatePedidoB2BFirmeAsync(ServiceReference1.CreatePedidoB2BFirmeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fibremex.com.mx/CreatePedidoB2B_withoutCreditFirme", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditFirmeResponse> CreatePedidoB2B_withoutCreditFirmeAsync(ServiceReference1.CreatePedidoB2B_withoutCreditFirmeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class Usuario
    {
        
        private string userKeyField;
        
        private string passwordField;
        
        private string societyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserKey
        {
            get
            {
                return this.userKeyField;
            }
            set
            {
                this.userKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Society
        {
            get
            {
                return this.societyField;
            }
            set
            {
                this.societyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class ResponseKey
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string errorTypeField;
        
        private Diccionary diccionaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Diccionary Diccionary
        {
            get
            {
                return this.diccionaryField;
            }
            set
            {
                this.diccionaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class Diccionary
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class ResponseString
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string errorTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class DocumentSalesQuotation
    {
        
        private string docNumEcommerceField;
        
        private string cardCodeField;
        
        private System.DateTime taxDateField;
        
        private System.DateTime docDueDateField;
        
        private System.DateTime docDateField;
        
        private string cFDIUserField;
        
        private string transferReferenceField;
        
        private int transportationCodeField;
        
        private int salesPersonCodeField;
        
        private int groupNumberField;
        
        private string paymentMethodField;
        
        private string numAtCardField;
        
        private string docCurrencyField;
        
        private string shipToCodeField;
        
        private string shipReferencesField;
        
        private string payToCodeField;
        
        private double docRateField;
        
        private ContactPerson contactPersonField;
        
        private Items_[] linesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocNumEcommerce
        {
            get
            {
                return this.docNumEcommerceField;
            }
            set
            {
                this.docNumEcommerceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardCode
        {
            get
            {
                return this.cardCodeField;
            }
            set
            {
                this.cardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TaxDate
        {
            get
            {
                return this.taxDateField;
            }
            set
            {
                this.taxDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DocDueDate
        {
            get
            {
                return this.docDueDateField;
            }
            set
            {
                this.docDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CFDIUser
        {
            get
            {
                return this.cFDIUserField;
            }
            set
            {
                this.cFDIUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TransferReference
        {
            get
            {
                return this.transferReferenceField;
            }
            set
            {
                this.transferReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TransportationCode
        {
            get
            {
                return this.transportationCodeField;
            }
            set
            {
                this.transportationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SalesPersonCode
        {
            get
            {
                return this.salesPersonCodeField;
            }
            set
            {
                this.salesPersonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int GroupNumber
        {
            get
            {
                return this.groupNumberField;
            }
            set
            {
                this.groupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NumAtCard
        {
            get
            {
                return this.numAtCardField;
            }
            set
            {
                this.numAtCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DocCurrency
        {
            get
            {
                return this.docCurrencyField;
            }
            set
            {
                this.docCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ShipToCode
        {
            get
            {
                return this.shipToCodeField;
            }
            set
            {
                this.shipToCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ShipReferences
        {
            get
            {
                return this.shipReferencesField;
            }
            set
            {
                this.shipReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PayToCode
        {
            get
            {
                return this.payToCodeField;
            }
            set
            {
                this.payToCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double DocRate
        {
            get
            {
                return this.docRateField;
            }
            set
            {
                this.docRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public ContactPerson ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=18)]
        public Items_[] Lines
        {
            get
            {
                return this.linesField;
            }
            set
            {
                this.linesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class ContactPerson
    {
        
        private string nameField;
        
        private string telphoneField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Telphone
        {
            get
            {
                return this.telphoneField;
            }
            set
            {
                this.telphoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class Items_
    {
        
        private string itemCodeField;
        
        private string descriptionField;
        
        private double quantityField;
        
        private double unitPriceField;
        
        private double discountPercentField;
        
        private string taxCodeField;
        
        private string warehouseCodeField;
        
        private double unitsOfMeasurmentField;
        
        private string currencyField;
        
        private int nCMCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double UnitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double DiscountPercent
        {
            get
            {
                return this.discountPercentField;
            }
            set
            {
                this.discountPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TaxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WarehouseCode
        {
            get
            {
                return this.warehouseCodeField;
            }
            set
            {
                this.warehouseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double UnitsOfMeasurment
        {
            get
            {
                return this.unitsOfMeasurmentField;
            }
            set
            {
                this.unitsOfMeasurmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int NCMCode
        {
            get
            {
                return this.nCMCodeField;
            }
            set
            {
                this.nCMCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class BussinesPartnerB2B
    {
        
        private DocumentSalesQuotation salesQuotationField;
        
        private ActionsWS actionsWSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocumentSalesQuotation SalesQuotation
        {
            get
            {
                return this.salesQuotationField;
            }
            set
            {
                this.salesQuotationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ActionsWS actionsWS
        {
            get
            {
                return this.actionsWSField;
            }
            set
            {
                this.actionsWSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class ActionsWS
    {
        
        private bool email_ItemsStockBadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Email_ItemsStockBad
        {
            get
            {
                return this.email_ItemsStockBadField;
            }
            set
            {
                this.email_ItemsStockBadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class ResponseKeys
    {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        private string errorTypeField;
        
        private Diccionary[] diccionaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorType
        {
            get
            {
                return this.errorTypeField;
            }
            set
            {
                this.errorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public Diccionary[] Diccionary
        {
            get
            {
                return this.diccionaryField;
            }
            set
            {
                this.diccionaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class DocumentInvoice
    {
        
        private string docNumEcommerceField;
        
        private string cardCodeField;
        
        private System.DateTime taxDateField;
        
        private System.DateTime docDueDateField;
        
        private System.DateTime docDateField;
        
        private double docRateField;
        
        private string cFDIUserField;
        
        private int transportationCodeField;
        
        private int salesPersonCodeField;
        
        private int groupNumberField;
        
        private string paymentMethodField;
        
        private string numAtCardField;
        
        private string docCurrencyField;
        
        private string transferReferenceField;
        
        private Items_[] linesField;
        
        private ContactPerson contactPersonField;
        
        private string shipReferencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DocNumEcommerce
        {
            get
            {
                return this.docNumEcommerceField;
            }
            set
            {
                this.docNumEcommerceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardCode
        {
            get
            {
                return this.cardCodeField;
            }
            set
            {
                this.cardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime TaxDate
        {
            get
            {
                return this.taxDateField;
            }
            set
            {
                this.taxDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DocDueDate
        {
            get
            {
                return this.docDueDateField;
            }
            set
            {
                this.docDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DocDate
        {
            get
            {
                return this.docDateField;
            }
            set
            {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double DocRate
        {
            get
            {
                return this.docRateField;
            }
            set
            {
                this.docRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CFDIUser
        {
            get
            {
                return this.cFDIUserField;
            }
            set
            {
                this.cFDIUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TransportationCode
        {
            get
            {
                return this.transportationCodeField;
            }
            set
            {
                this.transportationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SalesPersonCode
        {
            get
            {
                return this.salesPersonCodeField;
            }
            set
            {
                this.salesPersonCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int GroupNumber
        {
            get
            {
                return this.groupNumberField;
            }
            set
            {
                this.groupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string NumAtCard
        {
            get
            {
                return this.numAtCardField;
            }
            set
            {
                this.numAtCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DocCurrency
        {
            get
            {
                return this.docCurrencyField;
            }
            set
            {
                this.docCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TransferReference
        {
            get
            {
                return this.transferReferenceField;
            }
            set
            {
                this.transferReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        public Items_[] Lines
        {
            get
            {
                return this.linesField;
            }
            set
            {
                this.linesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public ContactPerson ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ShipReferences
        {
            get
            {
                return this.shipReferencesField;
            }
            set
            {
                this.shipReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class BussinessPartnerAdresses
    {
        
        private string streetField;
        
        private string streetNoField;
        
        private string blockField;
        
        private string countyField;
        
        private string zipCodeField;
        
        private string stateField;
        
        private string cityField;
        
        private string adressField;
        
        private string federalTaxIDField;
        
        private string cardNameField;
        
        private bool defaultField;
        
        private string addressTypeField;
        
        private string addressNameField;
        
        private ContactPerson contactPersonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StreetNo
        {
            get
            {
                return this.streetNoField;
            }
            set
            {
                this.streetNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Block
        {
            get
            {
                return this.blockField;
            }
            set
            {
                this.blockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ZipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Adress
        {
            get
            {
                return this.adressField;
            }
            set
            {
                this.adressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FederalTaxID
        {
            get
            {
                return this.federalTaxIDField;
            }
            set
            {
                this.federalTaxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CardName
        {
            get
            {
                return this.cardNameField;
            }
            set
            {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Default
        {
            get
            {
                return this.defaultField;
            }
            set
            {
                this.defaultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string AddressName
        {
            get
            {
                return this.addressNameField;
            }
            set
            {
                this.addressNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ContactPerson ContactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class DocumentBussinesPartner
    {
        
        private string cardCodeField;
        
        private string cardNameField;
        
        private string federalTaxIDField;
        
        private bool requiereInvoiceField;
        
        private BussinessPartnerAdresses shipToInformactionField;
        
        private BussinessPartnerAdresses billToInformactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CardCode
        {
            get
            {
                return this.cardCodeField;
            }
            set
            {
                this.cardCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CardName
        {
            get
            {
                return this.cardNameField;
            }
            set
            {
                this.cardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FederalTaxID
        {
            get
            {
                return this.federalTaxIDField;
            }
            set
            {
                this.federalTaxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool RequiereInvoice
        {
            get
            {
                return this.requiereInvoiceField;
            }
            set
            {
                this.requiereInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public BussinessPartnerAdresses ShipToInformaction
        {
            get
            {
                return this.shipToInformactionField;
            }
            set
            {
                this.shipToInformactionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public BussinessPartnerAdresses BillToInformaction
        {
            get
            {
                return this.billToInformactionField;
            }
            set
            {
                this.billToInformactionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fibremex.com.mx/")]
    public partial class BussinessPartnerB2C
    {
        
        private DocumentBussinesPartner partnerField;
        
        private DocumentInvoice documentField;
        
        private ActionsWS actionsWSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocumentBussinesPartner Partner
        {
            get
            {
                return this.partnerField;
            }
            set
            {
                this.partnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DocumentInvoice Document
        {
            get
            {
                return this.documentField;
            }
            set
            {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ActionsWS actionsWS
        {
            get
            {
                return this.actionsWSField;
            }
            set
            {
                this.actionsWSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2C", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2CRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinessPartnerB2C Invoice;
        
        public CreatePedidoB2CRequest()
        {
        }
        
        public CreatePedidoB2CRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinessPartnerB2C Invoice)
        {
            this.Usuario = Usuario;
            this.Invoice = Invoice;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2CResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2CResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKeys CreatePedidoB2CResult;
        
        public CreatePedidoB2CResponse()
        {
        }
        
        public CreatePedidoB2CResponse(ServiceReference1.ResponseKeys CreatePedidoB2CResult)
        {
            this.CreatePedidoB2CResult = CreatePedidoB2CResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2B", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2BRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public CreatePedidoB2BRequest()
        {
        }
        
        public CreatePedidoB2BRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2BResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2BResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKeys CreatePedidoB2BResult;
        
        public CreatePedidoB2BResponse()
        {
        }
        
        public CreatePedidoB2BResponse(ServiceReference1.ResponseKeys CreatePedidoB2BResult)
        {
            this.CreatePedidoB2BResult = CreatePedidoB2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2B_withoutCredit", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2B_withoutCreditRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public CreatePedidoB2B_withoutCreditRequest()
        {
        }
        
        public CreatePedidoB2B_withoutCreditRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2B_withoutCreditResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2B_withoutCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKeys CreatePedidoB2B_withoutCreditResult;
        
        public CreatePedidoB2B_withoutCreditResponse()
        {
        }
        
        public CreatePedidoB2B_withoutCreditResponse(ServiceReference1.ResponseKeys CreatePedidoB2B_withoutCreditResult)
        {
            this.CreatePedidoB2B_withoutCreditResult = CreatePedidoB2B_withoutCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRefDelivery", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class UpdateRefDeliveryRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public int NumEcommerce;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=1)]
        public System.DateTime DateDelivery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=2)]
        public string Received;
        
        public UpdateRefDeliveryRequest()
        {
        }
        
        public UpdateRefDeliveryRequest(ServiceReference1.Usuario Usuario, int NumEcommerce, System.DateTime DateDelivery, string Received)
        {
            this.Usuario = Usuario;
            this.NumEcommerce = NumEcommerce;
            this.DateDelivery = DateDelivery;
            this.Received = Received;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRefDeliveryResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class UpdateRefDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseString UpdateRefDeliveryResult;
        
        public UpdateRefDeliveryResponse()
        {
        }
        
        public UpdateRefDeliveryResponse(ServiceReference1.ResponseString UpdateRefDeliveryResult)
        {
            this.UpdateRefDeliveryResult = UpdateRefDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCotizacionFirmeB2B", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class AddCotizacionFirmeB2BRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public AddCotizacionFirmeB2BRequest()
        {
        }
        
        public AddCotizacionFirmeB2BRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCotizacionFirmeB2BResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class AddCotizacionFirmeB2BResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKey AddCotizacionFirmeB2BResult;
        
        public AddCotizacionFirmeB2BResponse()
        {
        }
        
        public AddCotizacionFirmeB2BResponse(ServiceReference1.ResponseKey AddCotizacionFirmeB2BResult)
        {
            this.AddCotizacionFirmeB2BResult = AddCotizacionFirmeB2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCotizacionFirmeB2B", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class UpdateCotizacionFirmeB2BRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public UpdateCotizacionFirmeB2BRequest()
        {
        }
        
        public UpdateCotizacionFirmeB2BRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCotizacionFirmeB2BResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class UpdateCotizacionFirmeB2BResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKey UpdateCotizacionFirmeB2BResult;
        
        public UpdateCotizacionFirmeB2BResponse()
        {
        }
        
        public UpdateCotizacionFirmeB2BResponse(ServiceReference1.ResponseKey UpdateCotizacionFirmeB2BResult)
        {
            this.UpdateCotizacionFirmeB2BResult = UpdateCotizacionFirmeB2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2BFirme", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2BFirmeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public CreatePedidoB2BFirmeRequest()
        {
        }
        
        public CreatePedidoB2BFirmeRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2BFirmeResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2BFirmeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKeys CreatePedidoB2BFirmeResult;
        
        public CreatePedidoB2BFirmeResponse()
        {
        }
        
        public CreatePedidoB2BFirmeResponse(ServiceReference1.ResponseKeys CreatePedidoB2BFirmeResult)
        {
            this.CreatePedidoB2BFirmeResult = CreatePedidoB2BFirmeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2B_withoutCreditFirme", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2B_withoutCreditFirmeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://fibremex.com.mx/")]
        public ServiceReference1.Usuario Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.BussinesPartnerB2B Document;
        
        public CreatePedidoB2B_withoutCreditFirmeRequest()
        {
        }
        
        public CreatePedidoB2B_withoutCreditFirmeRequest(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            this.Usuario = Usuario;
            this.Document = Document;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreatePedidoB2B_withoutCreditFirmeResponse", WrapperNamespace="http://fibremex.com.mx/", IsWrapped=true)]
    public partial class CreatePedidoB2B_withoutCreditFirmeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fibremex.com.mx/", Order=0)]
        public ServiceReference1.ResponseKeys CreatePedidoB2B_withoutCreditFirmeResult;
        
        public CreatePedidoB2B_withoutCreditFirmeResponse()
        {
        }
        
        public CreatePedidoB2B_withoutCreditFirmeResponse(ServiceReference1.ResponseKeys CreatePedidoB2B_withoutCreditFirmeResult)
        {
            this.CreatePedidoB2B_withoutCreditFirmeResult = CreatePedidoB2B_withoutCreditFirmeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WS_EcommerceSoapChannel : ServiceReference1.WS_EcommerceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WS_EcommerceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WS_EcommerceSoap>, ServiceReference1.WS_EcommerceSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_EcommerceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_EcommerceSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_EcommerceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_EcommerceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_EcommerceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_EcommerceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_EcommerceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_EcommerceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2CResponse> ServiceReference1.WS_EcommerceSoap.CreatePedidoB2CAsync(ServiceReference1.CreatePedidoB2CRequest request)
        {
            return base.Channel.CreatePedidoB2CAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2CResponse> CreatePedidoB2CAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinessPartnerB2C Invoice)
        {
            ServiceReference1.CreatePedidoB2CRequest inValue = new ServiceReference1.CreatePedidoB2CRequest();
            inValue.Usuario = Usuario;
            inValue.Invoice = Invoice;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).CreatePedidoB2CAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BResponse> ServiceReference1.WS_EcommerceSoap.CreatePedidoB2BAsync(ServiceReference1.CreatePedidoB2BRequest request)
        {
            return base.Channel.CreatePedidoB2BAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BResponse> CreatePedidoB2BAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.CreatePedidoB2BRequest inValue = new ServiceReference1.CreatePedidoB2BRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).CreatePedidoB2BAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditResponse> ServiceReference1.WS_EcommerceSoap.CreatePedidoB2B_withoutCreditAsync(ServiceReference1.CreatePedidoB2B_withoutCreditRequest request)
        {
            return base.Channel.CreatePedidoB2B_withoutCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditResponse> CreatePedidoB2B_withoutCreditAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.CreatePedidoB2B_withoutCreditRequest inValue = new ServiceReference1.CreatePedidoB2B_withoutCreditRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).CreatePedidoB2B_withoutCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateRefDeliveryResponse> ServiceReference1.WS_EcommerceSoap.UpdateRefDeliveryAsync(ServiceReference1.UpdateRefDeliveryRequest request)
        {
            return base.Channel.UpdateRefDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateRefDeliveryResponse> UpdateRefDeliveryAsync(ServiceReference1.Usuario Usuario, int NumEcommerce, System.DateTime DateDelivery, string Received)
        {
            ServiceReference1.UpdateRefDeliveryRequest inValue = new ServiceReference1.UpdateRefDeliveryRequest();
            inValue.Usuario = Usuario;
            inValue.NumEcommerce = NumEcommerce;
            inValue.DateDelivery = DateDelivery;
            inValue.Received = Received;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).UpdateRefDeliveryAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ResponseString> GetInforWsAsync()
        {
            return base.Channel.GetInforWsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddCotizacionFirmeB2BResponse> ServiceReference1.WS_EcommerceSoap.AddCotizacionFirmeB2BAsync(ServiceReference1.AddCotizacionFirmeB2BRequest request)
        {
            return base.Channel.AddCotizacionFirmeB2BAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddCotizacionFirmeB2BResponse> AddCotizacionFirmeB2BAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.AddCotizacionFirmeB2BRequest inValue = new ServiceReference1.AddCotizacionFirmeB2BRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).AddCotizacionFirmeB2BAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.UpdateCotizacionFirmeB2BResponse> ServiceReference1.WS_EcommerceSoap.UpdateCotizacionFirmeB2BAsync(ServiceReference1.UpdateCotizacionFirmeB2BRequest request)
        {
            return base.Channel.UpdateCotizacionFirmeB2BAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.UpdateCotizacionFirmeB2BResponse> UpdateCotizacionFirmeB2BAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.UpdateCotizacionFirmeB2BRequest inValue = new ServiceReference1.UpdateCotizacionFirmeB2BRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).UpdateCotizacionFirmeB2BAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BFirmeResponse> ServiceReference1.WS_EcommerceSoap.CreatePedidoB2BFirmeAsync(ServiceReference1.CreatePedidoB2BFirmeRequest request)
        {
            return base.Channel.CreatePedidoB2BFirmeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2BFirmeResponse> CreatePedidoB2BFirmeAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.CreatePedidoB2BFirmeRequest inValue = new ServiceReference1.CreatePedidoB2BFirmeRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).CreatePedidoB2BFirmeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditFirmeResponse> ServiceReference1.WS_EcommerceSoap.CreatePedidoB2B_withoutCreditFirmeAsync(ServiceReference1.CreatePedidoB2B_withoutCreditFirmeRequest request)
        {
            return base.Channel.CreatePedidoB2B_withoutCreditFirmeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreatePedidoB2B_withoutCreditFirmeResponse> CreatePedidoB2B_withoutCreditFirmeAsync(ServiceReference1.Usuario Usuario, ServiceReference1.BussinesPartnerB2B Document)
        {
            ServiceReference1.CreatePedidoB2B_withoutCreditFirmeRequest inValue = new ServiceReference1.CreatePedidoB2B_withoutCreditFirmeRequest();
            inValue.Usuario = Usuario;
            inValue.Document = Document;
            return ((ServiceReference1.WS_EcommerceSoap)(this)).CreatePedidoB2B_withoutCreditFirmeAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_EcommerceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_EcommerceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_EcommerceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.2.28:64615/WS_Ecommerce.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_EcommerceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.2.28:64615/WS_Ecommerce.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_EcommerceSoap,
            
            WS_EcommerceSoap12,
        }
    }
}
